-- This file enters all labels for class term into the database. 

INSERT INTO core_label (label_name, label_index, table_id_id)
VALUES
  ('cls_id', 1, (SELECT table_id FROM core_table WHERE table_name = 'Class Term')),
  ('trm_cd', 2, (SELECT table_id FROM core_table WHERE table_name = 'Class Term')),
  ('cls_nbr_id', 3, (SELECT table_id FROM core_table WHERE table_name = 'Class Term')),
  ('crs_id', 4, (SELECT table_id FROM core_table WHERE table_name = 'Class Term')),
  ('crs_cd', 5, (SELECT table_id FROM core_table WHERE table_name = 'Class Term')),
  ('crs_subject_cd', 6, (SELECT table_id FROM core_table WHERE table_name = 'Class Term')),
  ('crs_catalog_cd', 7, (SELECT table_id FROM core_table WHERE table_name = 'Class Term')),
  ('crs_catalog_extn_cd', 8, (SELECT table_id FROM core_table WHERE table_name = 'Class Term')),
  ('crs_descr', 9, (SELECT table_id FROM core_table WHERE table_name = 'Class Term')),
  ('crs_Id', 10, (SELECT table_id FROM core_table WHERE table_name = 'Class Term')),
  ('crs_topic_id', 11, (SELECT table_id FROM core_table WHERE table_name = 'Class Term')),
  ('crs_topic_descr', 12, (SELECT table_id FROM core_table WHERE table_name = 'Class Term')),
  ('cls_type_cd', 13, (SELECT table_id FROM core_table WHERE table_name = 'Class Term')),
  ('cls_type_ssr_cd', 14, (SELECT table_id FROM core_table WHERE table_name = 'Class Term')),
  ('cls_stat_sched_cd', 15, (SELECT table_id FROM core_table WHERE table_name = 'Class Term')),
  ('cls_stat_reg_flg', 16, (SELECT table_id FROM core_table WHERE table_name = 'Class Term')),
  ('cls_stat_display_search_flg', 17, (SELECT table_id FROM core_table WHERE table_name = 'Class Term')),
  ('cls_cmb_id', 18, (SELECT table_id FROM core_table WHERE table_name = 'Class Term')),
  ('crs_cmb_cd', 19, (SELECT table_id FROM core_table WHERE table_name = 'Class Term')),
  ('cls_ses_cd', 20, (SELECT table_id FROM core_table WHERE table_name = 'Class Term')),
  ('cls_unit_cd', 21, (SELECT table_id FROM core_table WHERE table_name = 'Class Term')),
  ('cls_coll_cd', 22, (SELECT table_id FROM core_table WHERE table_name = 'Class Term')),
  ('cls_coll_cmps_cd', 23, (SELECT table_id FROM core_table WHERE table_name = 'Class Term')),
  ('cls_prim_instr_id', 24, (SELECT table_id FROM core_table WHERE table_name = 'Class Term')),
  ('cls_start_dt', 25, (SELECT table_id FROM core_table WHERE table_name = 'Class Term')),
  ('cls_end_dt', 26, (SELECT table_id FROM core_table WHERE table_name = 'Class Term')),
  ('cls_modality_instrn_cd', 27, (SELECT table_id FROM core_table WHERE table_name = 'Class Term')),
  ('cls_modality_loc_descr', 28, (SELECT table_id FROM core_table WHERE table_name = 'Class Term')),
  ('cls_modality_extn_descr', 29, (SELECT table_id FROM core_table WHERE table_name = 'Class Term')),
  ('cls_loc_cmps_cd', 30, (SELECT table_id FROM core_table WHERE table_name = 'Class Term'));
