# Generated by Django 5.1.5 on 2025-01-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tooltips',
            options={'verbose_name': 'Tooltip', 'verbose_name_plural': 'Tooltips'},
        ),
        migrations.RemoveField(
            model_name='tooltips',
            name='tool_tip_description',
        ),
        migrations.RemoveField(
            model_name='tooltips',
            name='tool_tip_label',
        ),
        migrations.AddField(
            model_name='tooltips',
            name='Tooltip_Description',
            field=models.TextField(default='Please enter description', help_text='Enter the description for the tooltip'),
        ),
        migrations.AddField(
            model_name='tooltips',
            name='Tooltip_Label',
            field=models.CharField(default='Please enter description', help_text='Enter a descriptive lable for the tooltip', max_length=255),
            preserve_default=False,
        ),
    ]
