# Generated by Django 5.1.5 on 2025-01-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tooltips_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tooltips',
            name='Tooltip_Label',
            field=models.CharField(help_text='Enter a descriptive label for the tooltip', max_length=255),
        ),
    ]
