# Generated by Django 5.1.5 on 2025-01-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tooltips_tooltip_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the table', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the table')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the table was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the table was last updated')),
            ],
            options={
                'verbose_name': 'Table Name',
                'verbose_name_plural': 'Table Names',
            },
        ),
    ]
