# Generated by Django 5.1.5 on 2025-01-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tablename'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonDemographics',
            fields=[
                ('label', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('friendly_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('dataset_name', models.CharField(max_length=100)),
                ('sample_data', models.TextField(blank=True, null=True)),
                ('null_handling', models.BooleanField(default=True)),
                ('data_type', models.CharField(max_length=50)),
            ],
        ),
    ]
