# Generated by Django 5.1.5 on 2025-01-28 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_persondemographics'),
        ('core', '0005_studentclass'),
    ]

    operations = [
    ]
