# Generated by Django 5.1.5 on 2025-01-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_0005_persondemographics_0005_studentclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTerm',
            fields=[
                ('label', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('friendly_name', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('dataset_name', models.CharField(max_length=255)),
                ('sample_data', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Class Term',
                'verbose_name_plural': 'Class Terms',
                'db_table': 'class_term',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentTerm',
            fields=[
                ('label', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('friendly_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('dataset_name', models.CharField(max_length=100)),
                ('sample_data', models.TextField(blank=True, null=True)),
                ('null_handling', models.BooleanField(default=True)),
                ('data_type', models.CharField(max_length=50)),
                ('de_identified', models.BooleanField(default=False)),
                ('additional_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
