# Generated by Django 5.1.5 on 2025-02-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_classterm_studentterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasDiscussionEntryFields',
            fields=[
                ('label', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('friendly_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('dataset_name', models.CharField(max_length=100)),
                ('sample_data', models.TextField(blank=True, null=True)),
                ('null_handling', models.BooleanField()),
                ('data_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Canvas Discussion Entry Fields',
                'db_table': 'canvas_discussion_entry_fields',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentClassTable',
            fields=[
                ('category', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('friendly_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('source', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('dataset_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'student_class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('term_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, unique=True)),
                ('friendly_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('dataset_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sample_data', models.TextField(blank=True, null=True)),
                ('null_handling', models.CharField(blank=True, max_length=255, null=True)),
                ('de_identified', models.BooleanField(default=False)),
                ('additional_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
