# Generated by Django 5.1.5 on 2025-02-04 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_canvasdiscussionentryfields_studentclasstable_term'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentclasstable',
            options={'managed': True},
        ),
    ]
