# Generated by Django 5.1.6 on 2025-02-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_studentclasstable_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(db_index=True, help_text='Enter a category name', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('table_name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
                ('use_cases', models.TextField()),
                ('important_notes', models.TextField()),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'ordering': ['table_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='studentclasstable',
            options={'managed': False},
        ),
    ]
