# Generated by Django 5.1.6 on 2025-02-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_category_table_alter_studentclasstable_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('field_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('field_name', models.CharField(help_text='Enter the name of the field', max_length=100)),
                ('description', models.TextField(help_text='Provide a description of the field')),
                ('position', models.PositiveIntegerField(help_text='Position of the field in the table')),
                ('tables', models.ManyToManyField(blank=True, related_name='fields', to='core.table')),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
                'ordering': ['field_name'],
            },
        ),
    ]
