# Generated by Django 5.1.6 on 2025-02-20 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(db_index=True, help_text='Enter a category name', max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('label_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('label_name', models.CharField(help_text='Enter the name of the label', max_length=100)),
                ('label_index', models.PositiveBigIntegerField(help_text='Index of the label in the table')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.table')),
            ],
            options={
                'verbose_name': 'Label',
                'verbose_name_plural': 'Labels',
                'ordering': ['label_name'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('entry_content', models.TextField(help_text='Content of the entry')),
                ('field', models.ForeignKey(help_text='The field associated with this entry', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.field')),
                ('label', models.ForeignKey(help_text='The label associated with this entry', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.label')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
                'ordering': ['entry_id'],
            },
        ),
    ]
