# Generated by Django 5.1.6 on 2025-02-25 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_category_category_name_label_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
